### PR TITLE
Update mdtest number of files

### PR DESCRIPTION
**Pull request by berserk-fury**
Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>

### CODE REVIEW

**Comment by berserk-fury** [comment]
I think that we need to keep `'sw_time': '60'` rather than 90. Otherwise pretty much all the mdtest runs hit a  `DER_NOSPACE(-1007): 'No space on storage target'`.

**Comment by daltonbohning** [comment]
> I think that we need to keep `'sw_time': '60'` rather than 90. Otherwise pretty much all the mdtest runs hit a `DER_NOSPACE(-1007): 'No space on storage target'`.

If we keep `'sw_time': '60'`, does that mean some of the tests need to be re-ran that were shown yesterday in the performance WG?
(I think some tests used 90 and some used 60 - not sure if it makes a big difference for the final metrics)

**Comment by daltonbohning** [comment]
> No need to re run. Those tests ran using 60s. I suggest to take a look at the raw results. I thin that it could be really helpful to get familar with all the logs and data that these scripts collects :)
> They are available on Wolf
> `/home/eduardoj/frontera/21WW15.2`
> 
> The big difference between using 60s and 90s for `mdtest` is basically passing or failing the test.

Thanks, I'll take a look!

**Review by daltonbohning — APPROVED** [review]
LGTM

**Pull request merged**
